# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import email_pb2 as email__pb2


class EmailHelperStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmails = channel.unary_unary(
                '/email.EmailHelper/GetEmails',
                request_serializer=email__pb2.EmailRequest.SerializeToString,
                response_deserializer=email__pb2.EmailReply.FromString,
                )


class EmailHelperServicer(object):
    """The greeting service definition.
    """

    def GetEmails(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailHelperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmails,
                    request_deserializer=email__pb2.EmailRequest.FromString,
                    response_serializer=email__pb2.EmailReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'email.EmailHelper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmailHelper(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetEmails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/email.EmailHelper/GetEmails',
            email__pb2.EmailRequest.SerializeToString,
            email__pb2.EmailReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
