# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bparse.proto\x12\x05parse\"=\n\x13\x45mailContentRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_info\x18\x02 \x01(\t\"\"\n\x0f\x45mailParseReply\x12\x0f\n\x07message\x18\x01 \x01(\t2L\n\x06Parser\x12\x42\n\nParseEmail\x12\x1a.parse.EmailContentRequest\x1a\x16.parse.EmailParseReply\"\x00\x42#\n\rio.grpc.parseB\nParseProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rio.grpc.parseB\nParseProtoP\001\242\002\003HLW'
  _EMAILCONTENTREQUEST._serialized_start=22
  _EMAILCONTENTREQUEST._serialized_end=83
  _EMAILPARSEREPLY._serialized_start=85
  _EMAILPARSEREPLY._serialized_end=119
  _PARSER._serialized_start=121
  _PARSER._serialized_end=197
# @@protoc_insertion_point(module_scope)
