# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import parse_pb2 as parse__pb2


class ParserStub(object):
    """The email parse service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseEmail = channel.unary_unary(
                '/parse.Parser/ParseEmail',
                request_serializer=parse__pb2.EmailContentRequest.SerializeToString,
                response_deserializer=parse__pb2.EmailParseReply.FromString,
                )


class ParserServicer(object):
    """The email parse service definition.
    """

    def ParseEmail(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseEmail,
                    request_deserializer=parse__pb2.EmailContentRequest.FromString,
                    response_serializer=parse__pb2.EmailParseReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parse.Parser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Parser(object):
    """The email parse service definition.
    """

    @staticmethod
    def ParseEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/parse.Parser/ParseEmail',
            parse__pb2.EmailContentRequest.SerializeToString,
            parse__pb2.EmailParseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
