// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: email.proto

package email_grpc_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailHelperClient is the client API for EmailHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailHelperClient interface {
	// Sends a greeting
	GetEmails(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error)
}

type emailHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailHelperClient(cc grpc.ClientConnInterface) EmailHelperClient {
	return &emailHelperClient{cc}
}

func (c *emailHelperClient) GetEmails(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailReply, error) {
	out := new(EmailReply)
	err := c.cc.Invoke(ctx, "/email.EmailHelper/GetEmails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailHelperServer is the server API for EmailHelper service.
// All implementations must embed UnimplementedEmailHelperServer
// for forward compatibility
type EmailHelperServer interface {
	// Sends a greeting
	GetEmails(context.Context, *EmailRequest) (*EmailReply, error)
	mustEmbedUnimplementedEmailHelperServer()
}

// UnimplementedEmailHelperServer must be embedded to have forward compatible implementations.
type UnimplementedEmailHelperServer struct {
}

func (UnimplementedEmailHelperServer) GetEmails(context.Context, *EmailRequest) (*EmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmails not implemented")
}
func (UnimplementedEmailHelperServer) mustEmbedUnimplementedEmailHelperServer() {}

// UnsafeEmailHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailHelperServer will
// result in compilation errors.
type UnsafeEmailHelperServer interface {
	mustEmbedUnimplementedEmailHelperServer()
}

func RegisterEmailHelperServer(s grpc.ServiceRegistrar, srv EmailHelperServer) {
	s.RegisterService(&EmailHelper_ServiceDesc, srv)
}

func _EmailHelper_GetEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailHelperServer).GetEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.EmailHelper/GetEmails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailHelperServer).GetEmails(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailHelper_ServiceDesc is the grpc.ServiceDesc for EmailHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "email.EmailHelper",
	HandlerType: (*EmailHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmails",
			Handler:    _EmailHelper_GetEmails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
