// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: parse.proto

package parse_grpc_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type EmailContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email          string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	AdditionalInfo string `protobuf:"bytes,2,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
}

func (x *EmailContentRequest) Reset() {
	*x = EmailContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailContentRequest) ProtoMessage() {}

func (x *EmailContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailContentRequest.ProtoReflect.Descriptor instead.
func (*EmailContentRequest) Descriptor() ([]byte, []int) {
	return file_parse_proto_rawDescGZIP(), []int{0}
}

func (x *EmailContentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailContentRequest) GetAdditionalInfo() string {
	if x != nil {
		return x.AdditionalInfo
	}
	return ""
}

// The response message containing the greetings
type EmailParseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EmailParseReply) Reset() {
	*x = EmailParseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailParseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailParseReply) ProtoMessage() {}

func (x *EmailParseReply) ProtoReflect() protoreflect.Message {
	mi := &file_parse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailParseReply.ProtoReflect.Descriptor instead.
func (*EmailParseReply) Descriptor() ([]byte, []int) {
	return file_parse_proto_rawDescGZIP(), []int{1}
}

func (x *EmailParseReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_parse_proto protoreflect.FileDescriptor

var file_parse_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x61, 0x72, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x13, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2b, 0x0a, 0x0f, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4c, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x72, 0x12, 0x42, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x61,
	0x72, 0x73, 0x65, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x53, 0x0a, 0x0d, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x42, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x77, 0x69, 0x7a, 0x61,
	0x72, 0x64, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0xa2, 0x02, 0x03, 0x48, 0x4c, 0x57, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_parse_proto_rawDescOnce sync.Once
	file_parse_proto_rawDescData = file_parse_proto_rawDesc
)

func file_parse_proto_rawDescGZIP() []byte {
	file_parse_proto_rawDescOnce.Do(func() {
		file_parse_proto_rawDescData = protoimpl.X.CompressGZIP(file_parse_proto_rawDescData)
	})
	return file_parse_proto_rawDescData
}

var file_parse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parse_proto_goTypes = []interface{}{
	(*EmailContentRequest)(nil), // 0: parse.EmailContentRequest
	(*EmailParseReply)(nil),     // 1: parse.EmailParseReply
}
var file_parse_proto_depIdxs = []int32{
	0, // 0: parse.Parser.ParseEmail:input_type -> parse.EmailContentRequest
	1, // 1: parse.Parser.ParseEmail:output_type -> parse.EmailParseReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parse_proto_init() }
func file_parse_proto_init() {
	if File_parse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailParseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parse_proto_goTypes,
		DependencyIndexes: file_parse_proto_depIdxs,
		MessageInfos:      file_parse_proto_msgTypes,
	}.Build()
	File_parse_proto = out.File
	file_parse_proto_rawDesc = nil
	file_parse_proto_goTypes = nil
	file_parse_proto_depIdxs = nil
}
